services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: main_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - '3306:3306'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 3000:80
    depends_on:
      - backend